add relokia pm data migration
basecamp/bc3-integrations pull request #174
Opened 2021-06-18 11:21 UTC by mktg-relokia

2021-06-18 19:30 UTC, rosa requested changes

2021-06-18 19:30 UTC, rosa commented on integrations.yml
> +  name: "Basecamp Migration"
This is intended to be the name of the app, so should it be `Relokia`?

2021-06-30 06:25 UTC, rosa approved these changes

2021-06-30 06:26 UTC, merged

2021-08-23 09:15 UTC, relokia commented
Hi Rosa!

Could you, please, help, I can't see our app listed on Basecamp 3.